name = "hello-world-sriyan"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "hello-world-sriyan_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "hello-world-sriyan.wasm"
command = "npm run build:release"
